// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RecomandationSystem.Application;

#nullable disable

namespace RecomandationSystem.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecomandationSystem.Application.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding1024")
                        .HasColumnType("vector(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Brand = "Samsung",
                            Category = 0,
                            Description = "Latest flagship smartphone with AMOLED display",
                            Name = "Smartphone X10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Brand = "Sony",
                            Category = 0,
                            Description = "Noise-cancelling wireless earbuds with 30hr battery",
                            Name = "Wireless Earbuds Pro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Brand = "LG",
                            Category = 0,
                            Description = "55-inch smart TV with HDR support",
                            Name = "4K Ultra HD TV"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Brand = "ASUS",
                            Category = 0,
                            Description = "High-performance laptop with RTX graphics",
                            Name = "Gaming Laptop"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Brand = "Apple",
                            Category = 0,
                            Description = "Fitness tracker with heart rate monitoring",
                            Name = "Smart Watch"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Brand = "JBL",
                            Category = 0,
                            Description = "Portable waterproof speaker with 20W output",
                            Name = "Bluetooth Speaker"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Brand = "Canon",
                            Category = 0,
                            Description = "24MP camera with 4K video recording",
                            Name = "DSLR Camera"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Brand = "Microsoft",
                            Category = 0,
                            Description = "10-inch tablet with stylus support",
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Brand = "Bose",
                            Category = 0,
                            Description = "Over-ear headphones with 40hr battery life",
                            Name = "Noise Cancelling Headphones"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Brand = "Amazon",
                            Category = 0,
                            Description = "Paper-like display with adjustable front light",
                            Name = "E-Reader"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Brand = "GoPro",
                            Category = 0,
                            Description = "Waterproof camera with 4K/60fps video",
                            Name = "Action Camera"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Brand = "SanDisk",
                            Category = 0,
                            Description = "1TB portable SSD with USB 3.2 interface",
                            Name = "External SSD"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Brand = "Belkin",
                            Category = 0,
                            Description = "15W fast charging pad for smartphones",
                            Name = "Wireless Charger"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Brand = "Google",
                            Category = 0,
                            Description = "Central control for all smart home devices",
                            Name = "Smart Home Hub"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Brand = "Meta",
                            Category = 0,
                            Description = "Immersive virtual reality experience",
                            Name = "VR Headset"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Brand = "Samsung",
                            Category = 1,
                            Description = "French door fridge with ice maker",
                            Name = "Refrigerator"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Brand = "LG",
                            Category = 1,
                            Description = "Front load washer with steam function",
                            Name = "Washing Machine"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Brand = "Panasonic",
                            Category = 1,
                            Description = "Convection microwave with grill",
                            Name = "Microwave Oven"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Brand = "Daikin",
                            Category = 1,
                            Description = "Inverter split AC with wifi control",
                            Name = "Air Conditioner"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Brand = "iRobot",
                            Category = 1,
                            Description = "Self-charging robot vacuum with mapping",
                            Name = "Robot Vacuum"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Brand = "Vitamix",
                            Category = 1,
                            Description = "High-speed blender with 6 preset programs",
                            Name = "Blender"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Brand = "Keurig",
                            Category = 1,
                            Description = "Programmable 12-cup coffee machine",
                            Name = "Coffee Maker"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Brand = "Cuisinart",
                            Category = 1,
                            Description = "12-cup capacity with multiple attachments",
                            Name = "Food Processor"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Brand = "KitchenAid",
                            Category = 1,
                            Description = "Professional grade kitchen mixer",
                            Name = "Stand Mixer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Brand = "Ninja",
                            Category = 1,
                            Description = "Digital air fryer with 8 cooking presets",
                            Name = "Air Fryer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Brand = "Nike",
                            Category = 2,
                            Description = "100% cotton crew neck t-shirt",
                            Name = "Men's T-Shirt"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Brand = "Levi's",
                            Category = 2,
                            Description = "Slim fit stretch denim jeans",
                            Name = "Women's Jeans"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Brand = "The North Face",
                            Category = 2,
                            Description = "Waterproof down jacket for cold weather",
                            Name = "Winter Jacket"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Brand = "Adidas",
                            Category = 2,
                            Description = "Lightweight shoes with cushioned soles",
                            Name = "Running Shoes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Brand = "Hugo Boss",
                            Category = 2,
                            Description = "Formal business shirt with slim fit",
                            Name = "Dress Shirt"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Brand = "Lululemon",
                            Category = 2,
                            Description = "High-waisted leggings with moisture-wicking fabric",
                            Name = "Yoga Pants"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Brand = "Zara",
                            Category = 2,
                            Description = "Floral print sundress with ruffled sleeves",
                            Name = "Summer Dress"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            Brand = "Gucci",
                            Category = 2,
                            Description = "Genuine leather belt with metal buckle",
                            Name = "Leather Belt"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            Brand = "Ralph Lauren",
                            Category = 2,
                            Description = "Cable knit sweater in various colors",
                            Name = "Wool Sweater"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            Brand = "Speedo",
                            Category = 2,
                            Description = "Quick-dry swim shorts with mesh lining",
                            Name = "Swim Trunks"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            Brand = "New Era",
                            Category = 2,
                            Description = "Adjustable cotton twill cap",
                            Name = "Baseball Cap"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            Brand = "Hermès",
                            Category = 2,
                            Description = "Luxury printed silk scarf",
                            Name = "Silk Scarf"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            Brand = "Canada Goose",
                            Category = 2,
                            Description = "Insulated touchscreen-compatible gloves",
                            Name = "Winter Gloves"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            Brand = "Under Armour",
                            Category = 2,
                            Description = "6-pack of cushioned athletic socks",
                            Name = "Socks Pack"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            Brand = "Wrangler",
                            Category = 2,
                            Description = "Classic blue denim jacket with pockets",
                            Name = "Denim Jacket"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            Brand = "IKEA",
                            Category = 3,
                            Description = "Decorative pillow with geometric pattern",
                            Name = "Throw Pillow"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            Brand = "Brooklinen",
                            Category = 3,
                            Description = "1000 thread count Egyptian cotton sheets",
                            Name = "Bed Sheet Set"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            Brand = "Corelle",
                            Category = 3,
                            Description = "16-piece porcelain dinner set",
                            Name = "Dinnerware Set"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            Brand = "Ruggable",
                            Category = 3,
                            Description = "5x7 ft wool rug with traditional design",
                            Name = "Area Rug"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            Brand = "West Elm",
                            Category = 3,
                            Description = "Modern LED lamp with dimmable light",
                            Name = "Table Lamp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            Brand = "Etsy",
                            Category = 3,
                            Description = "Framed canvas print of abstract painting",
                            Name = "Wall Art"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            Brand = "All-Clad",
                            Category = 3,
                            Description = "10-piece non-stick cookware set",
                            Name = "Cookware Set"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            Brand = "Parachute",
                            Category = 3,
                            Description = "6-piece luxury cotton towel set",
                            Name = "Bath Towel Set"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            Brand = "Pottery Barn",
                            Category = 3,
                            Description = "Blackout curtains with thermal insulation",
                            Name = "Curtains"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            Brand = "The Container Store",
                            Category = 3,
                            Description = "Set of 3 woven storage baskets",
                            Name = "Storage Baskets"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            Brand = "CeraVe",
                            Category = 4,
                            Description = "24-hour hydration facial moisturizer",
                            Name = "Moisturizing Cream"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            Brand = "Olaplex",
                            Category = 4,
                            Description = "Sulfate-free shampoo for all hair types",
                            Name = "Shampoo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000053"),
                            Brand = "MAC",
                            Category = 4,
                            Description = "Long-wear matte lipstick in 12 shades",
                            Name = "Lipstick"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000054"),
                            Brand = "Chanel",
                            Category = 4,
                            Description = "Eau de parfum with floral notes",
                            Name = "Perfume"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000055"),
                            Brand = "Oral-B",
                            Category = 4,
                            Description = "Sonic toothbrush with 3 cleaning modes",
                            Name = "Electric Toothbrush"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000056"),
                            Brand = "La Roche-Posay",
                            Category = 4,
                            Description = "Gentle foaming cleanser for sensitive skin",
                            Name = "Facial Cleanser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000057"),
                            Brand = "Dyson",
                            Category = 4,
                            Description = "Professional ionic hair dryer",
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000058"),
                            Brand = "OPI",
                            Category = 4,
                            Description = "6-piece set of long-lasting nail colors",
                            Name = "Nail Polish Set"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000059"),
                            Brand = "Morphe",
                            Category = 4,
                            Description = "12-piece vegan makeup brush collection",
                            Name = "Makeup Brush Set"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000060"),
                            Brand = "Neutrogena",
                            Category = 4,
                            Description = "SPF 50 broad spectrum protection",
                            Name = "Sunscreen Lotion"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000061"),
                            Brand = "Manduka",
                            Category = 5,
                            Description = "Non-slip eco-friendly yoga mat",
                            Name = "Yoga Mat"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000062"),
                            Brand = "Bowflex",
                            Category = 5,
                            Description = "Adjustable dumbbells 5-25 lbs",
                            Name = "Dumbbell Set"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000063"),
                            Brand = "Garmin",
                            Category = 5,
                            Description = "GPS running watch with heart rate monitor",
                            Name = "Running Watch"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000064"),
                            Brand = "Spalding",
                            Category = 5,
                            Description = "Official size 7 basketball",
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000065"),
                            Brand = "Wilson",
                            Category = 5,
                            Description = "Graphite racket with vibration dampening",
                            Name = "Tennis Racket"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000066"),
                            Brand = "Specialized",
                            Category = 5,
                            Description = "Lightweight aerodynamic bike helmet",
                            Name = "Cycling Helmet"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000067"),
                            Brand = "Fitbit",
                            Category = 5,
                            Description = "Water-resistant activity tracker",
                            Name = "Fitness Tracker"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000068"),
                            Brand = "TheraBand",
                            Category = 5,
                            Description = "Set of 5 latex resistance bands",
                            Name = "Resistance Bands"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000069"),
                            Brand = "Osprey",
                            Category = 5,
                            Description = "30L waterproof hiking backpack",
                            Name = "Hiking Backpack"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000070"),
                            Brand = "Arena",
                            Category = 5,
                            Description = "Anti-fog UV protection swim goggles",
                            Name = "Swim Goggles"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000071"),
                            Brand = "Penguin",
                            Category = 6,
                            Description = "Award-winning fiction book",
                            Name = "Bestselling Novel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000072"),
                            Brand = "Williams Sonoma",
                            Category = 6,
                            Description = "Collection of 100 easy recipes",
                            Name = "Cookbook"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000073"),
                            Brand = "Simon & Schuster",
                            Category = 6,
                            Description = "Guide to personal development",
                            Name = "Self-Help Book"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000074"),
                            Brand = "Scholastic",
                            Category = 6,
                            Description = "Illustrated storybook for ages 4-8",
                            Name = "Children's Book"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000075"),
                            Brand = "Pearson",
                            Category = 6,
                            Description = "University level physics textbook",
                            Name = "Science Textbook"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000076"),
                            Brand = "Lonely Planet",
                            Category = 6,
                            Description = "Comprehensive city travel guide",
                            Name = "Travel Guide"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000077"),
                            Brand = "Random House",
                            Category = 6,
                            Description = "Life story of famous historical figure",
                            Name = "Biography"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000078"),
                            Brand = "Taschen",
                            Category = 6,
                            Description = "Collection of famous paintings",
                            Name = "Art Book"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000079"),
                            Brand = "Faber & Faber",
                            Category = 6,
                            Description = "Contemporary poetry anthology",
                            Name = "Poetry Collection"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000080"),
                            Brand = "Harvard Business Review",
                            Category = 6,
                            Description = "Guide to entrepreneurship",
                            Name = "Business Book"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000081"),
                            Brand = "LEGO",
                            Category = 7,
                            Description = "100-piece interlocking building set",
                            Name = "Building Blocks"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000082"),
                            Brand = "Barbie",
                            Category = 7,
                            Description = "Interactive doll with accessories",
                            Name = "Doll"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000083"),
                            Brand = "Traxxas",
                            Category = 7,
                            Description = "1:18 scale RC car with 2.4GHz remote",
                            Name = "Remote Control Car"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000084"),
                            Brand = "Hasbro",
                            Category = 7,
                            Description = "Family strategy board game",
                            Name = "Board Game"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000085"),
                            Brand = "Ravensburger",
                            Category = 7,
                            Description = "1000-piece jigsaw puzzle",
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000086"),
                            Brand = "Steiff",
                            Category = 7,
                            Description = "Plush teddy bear",
                            Name = "Stuffed Animal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000087"),
                            Brand = "Thames & Kosmos",
                            Category = 7,
                            Description = "STEM learning kit for kids",
                            Name = "Science Kit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000088"),
                            Brand = "Hot Toys",
                            Category = 7,
                            Description = "Collectible movie character figure",
                            Name = "Action Figure"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000089"),
                            Brand = "KidKraft",
                            Category = 7,
                            Description = "Miniature kitchen with accessories",
                            Name = "Play Kitchen"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000090"),
                            Brand = "Crayola",
                            Category = 7,
                            Description = "Deluxe art supplies for children",
                            Name = "Art Set"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000091"),
                            Brand = "Lavazza",
                            Category = 8,
                            Description = "Premium arabica whole bean coffee",
                            Name = "Organic Coffee"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000092"),
                            Brand = "Lindt",
                            Category = 8,
                            Description = "70% cocoa dark chocolate bar",
                            Name = "Dark Chocolate"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000093"),
                            Brand = "Colavita",
                            Category = 8,
                            Description = "Extra virgin cold-pressed olive oil",
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000094"),
                            Brand = "Kind",
                            Category = 8,
                            Description = "Gluten-free almond honey granola",
                            Name = "Granola"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000095"),
                            Brand = "Twinings",
                            Category = 8,
                            Description = "Assorted premium tea collection",
                            Name = "Tea Selection"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000096"),
                            Brand = "iOttie",
                            Category = 9,
                            Description = "Dashboard smartphone holder",
                            Name = "Car Phone Mount"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000097"),
                            Brand = "NOCO",
                            Category = 9,
                            Description = "Portable car battery jump starter",
                            Name = "Jump Starter"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000098"),
                            Brand = "Black+Decker",
                            Category = 9,
                            Description = "Handheld cordless car vacuum cleaner",
                            Name = "Car Vacuum"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000099"),
                            Brand = "Accutire",
                            Category = 9,
                            Description = "Digital tire pressure monitor",
                            Name = "Tire Pressure Gauge"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000100"),
                            Brand = "Meguiar's",
                            Category = 9,
                            Description = "Premium liquid car wax",
                            Name = "Car Wax"
                        });
                });

            modelBuilder.Entity("RecomandationSystem.Application.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Vector>("CombinedEmbedding1024")
                        .HasColumnType("vector(1024)");

                    b.Property<int>("UserGender")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecomandationSystem.Application.Models.Product", b =>
                {
                    b.HasOne("RecomandationSystem.Application.Models.User", null)
                        .WithMany("BuyedProducts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("RecomandationSystem.Application.Models.User", b =>
                {
                    b.Navigation("BuyedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
